AI-Friendly Documentation Link Validator
==================================================
Discovering markdown files...
Traceback (most recent call last):
  File "link_validator.py", line 560, in <module>
    main()
  File "link_validator.py", line 523, in main
    validator.discover_markdown_files()
  File "link_validator.py", line 39, in discover_markdown_files
    self.markdown_files = list(self.docs_root.rglob("*.md"))
  File "C:\ProgramData\Anaconda3\lib\pathlib.py", line 1090, in rglob
    for p in selector.select_from(self):
  File "C:\ProgramData\Anaconda3\lib\pathlib.py", line 559, in _select_from
    for starting_point in self._iterate_directories(parent_path, is_dir, scandir):
  File "C:\ProgramData\Anaconda3\lib\pathlib.py", line 549, in _iterate_directories
    for p in self._iterate_directories(path, is_dir, scandir):
  File "C:\ProgramData\Anaconda3\lib\pathlib.py", line 549, in _iterate_directories
    for p in self._iterate_directories(path, is_dir, scandir):
  File "C:\ProgramData\Anaconda3\lib\pathlib.py", line 549, in _iterate_directories
    for p in self._iterate_directories(path, is_dir, scandir):
  [Previous line repeated 984 more times]
  File "C:\ProgramData\Anaconda3\lib\pathlib.py", line 545, in _iterate_directories
    entries = list(scandir(parent_path))
  File "C:\ProgramData\Anaconda3\lib\pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
RecursionError: maximum recursion depth exceeded
